---

- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: remove docker
  apt:
    name: "{{item}}"
    state: absent
    update_cache: yes
  loop:
    - docker
    - docker.io
    - containerd
    - runc

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Create Docker group
  group: 
    name: docker 
    state: present

- name: Add current {{ ansible_env.USER }} to Docker group
  user: 
    name: "{{ ansible_env.USER }}" 
    groups: docker 
    append: yes

- name: Install docker-compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/{{ docker.docker_compose_version }}/docker-compose-Linux-x86_64" 
    dest: /usr/local/bin/docker-compose 
    force: no 
    mode: 0755
