---

- name: Install gnupg 
  become: true
  apt:
    name: gnupg
    state: latest

- name: Public Key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
    state: present

- name: install dependencies
  become: true
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
  args:
    warn: no

- name: Update cache 
  apt:
    update_cache: yes

- name: Install mongodb 
  become: true
  apt:
    name: mongodb
    state: latest

- name: Install mongocli
  become: true
  apt: 
    name: mongocli
    state: latest