---
zsh_user:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"
zsh_ohmy_theme: powerlevel10k/powerlevel10k

zsh_ohmy_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
  - name: zsh-completions
    repo: "https://github.com/zsh-users/zsh-completions"


zsh_ohmy_custom_themes:
  - name: powerlevel10k
    repo: "https://github.com/romkatv/powerlevel10k.git"

zsh_ohmy_plugins:
  - git
  - git-flow
  - docker
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh-completions
  - kubectl
  - brew
  - ansible
  - terraform

zsh_ohmy_alias:
  - alias k="kubectl"
  - alias kx="kubectx"
  - alias kn="kubens"
  - alias code="/mnt/c/Users/{{ ansible_env.USER }}*/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code"

zsh_ohmy_eval:
  - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

zsh_ohmy_disable_auto_update: false

zsh_append_zshrc: ""

zsh_debug_startup_time: false

