---
- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: no
  tags: configuration

- name: Switch to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  tags: configuration
  become: true

- name: Clone oh-my-zsh repository
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    accept_hostkey: yes
    update: yes
  tags: configuration

- name: Clone oh-my-zsh custom plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    clone: yes
    update: yes
  with_items: "{{ zsh_ohmy_custom_plugins }}"
  become: true
  tags: configuration

- name: Clone oh-my-zsh custom themes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/{{ item.name }}"
    accept_hostkey: yes
    update: yes
  with_items: "{{ zsh_ohmy_custom_themes }}"
  tags: configuration

- name: Create zsh config file
  template:
    src: zsh.config.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0640
  tags: configuration