---

- name: Install Python packages
  become: true
  apt: 
    pkg: ["python3", "python3-setuptools", "python3-dev", "python3-pip" ]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

- name: Install bottle python package
  pip:
    name: 
      - requests
      - boto3
      - botocore
      - colorama
      - docutils
      - jmespath   
      - pyasn1
      - python-dateutil  
      - PyYAML 
      - rsa 
      - s3transfer
      - setuptools
      - six
      - urllib3  
      - virtualenv
      - wheel
    extra_args: --upgrade